In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import csv
import difflib
import re

In [2]:
df = pd.DataFrame.from_csv('/home/claire/Documents/jobs/milieu/milieu-noumea/noumea-analysis/noumea-aug31.csv', header=0, sep=',', index_col=0)
df

,id,age,neighbourhood,lives_in_noumea,months_lived_in_noumea,email,enable_receive_emails,Étages: espaces educatifs,Bâtiments fermés au public pour réhabilitation,Maison du projet (accueil/ exposition),...,q4-9,q5-1,q5-2,q5-3,q5-4,q5-5,q5-6,q5-7,q5-8,q5-9
4,1,26.0,pk6,True,2 ans,jonathan.rebouillon@gmail.com,True,5,4,5,...,4,5,1,3,2,5,5,4,5,5
5,2,30.0,Magenta,True,30,Olivia.kurt@gmail.com,False,3,3,3,...,5,3,3,3,3,4,4,4,4,4
7,3,32.0,Trianon,True,22,ornc44@gmail.com,False,1,1,1,...,5,3,1,1,1,1,1,1,5,3
8,4,28.0,NaN,False,NaN,e.launay@live.fr,True,3,3,4,...,5,3,3,4,3,3,3,1,5,5
9,5,26.0,Baie des citrons,True,26 ans,haguet.megane@gmail.com,True,4,3,4,...,4,3,3,4,2,3,3,3,4,4
10,6,29.0,Magenta,True,4,NaN,False,3,3,3,...,3,1,3,3,3,4,3,3,3,4
11,7,46.0,Tuband,True,10,fgambarotto@yahoo.fr,False,3,3,3,...,3,4,3,3,4,4,3,3,3,3
12,8,46.0,Tuband,True,10,fgambarotto@yahoo.fr,True,3,3,3,...,3,4,3,3,4,4,3,3,3,3
13,9,37.0,Trianon,True,3 ans,marie.brenon@lagoon.nc,True,5,5,4,...,3,5,4,4,4,3,3,5,4,3
15,10,29.0,faubourg Blanchot,True,1,marie.c.22@hotmail.fr,True,3,3,3,...,5,4,3,3,3,3,3,4,4,4
16,11,63.0,Trianon,True,12,micalonc@gmail.com,True,3,3,3,...,3,3,3,3,3,3,3,3,3,3
17,12,48.0,VDC,True,14,hregimbe@yahoo.fr,True,3,2,2,...,3,5,3,5,3,3,3,3,3,3
18,13,25.0,ouémo,True,25 ans,boris.valin@gmail.com,True,2,3,2,...,5,5,5,5,5,5,5,5,5,5
20,14,31.0,Koutio,True,NaN,hnatrsnj@hotmail.com,False,3,3,3,...,3,3,2,4,2,3,2,5,5,4
21,15,47.0,ouemo,True,10 ans,sjouault@gmail.com,True,3,3,3,...,5,3,3,3,3,3,3,3,3,4
22,16,36.0,Tina,True,NaN,gilamii@free.fr,True,3,4,2,...,5,3,3,5,3,5,2,3,3,5
23,17,30.0,Magenta,True,5,NaN,False,4,4,2,...,3,2,3,3,4,4,3,3,5,1
24,18,35.0,7emekm,True,9,caledoguide@gmail.com,True,4,3,4,...,4,4,2,2,2,4,1,3,4,4
25,19,36.0,7em,True,8 ans,franck.dominici@gmail.com,True,5,5,5,...,5,5,4,4,4,5,4,4,4,5
26,20,26.0,NaN,False,NaN,amd.brt@gmail.com,True,3,3,3,...,5,5,3,3,4,3,3,3,3,5
27,21,31.0,NaN,False,NaN,sarltemad@gmail.com,False,4,4,4,...,4,4,4,4,4,4,4,4,4,4
28,22,NaN,NaN,False,NaN,NaN,False,3,3,3,...,3,1,1,1,1,1,1,1,1,1
29,23,30.0,Vallee des colons,True,4 ans,NaN,False,4,1,4,...,1,3,1,3,1,4,2,2,1,3
30,24,28.0,Faubourg,True,NaN,Caroline.frickbaconnais@gmail.com,False,2,2,3,...,2,2,3,3,3,3,3,3,3,3
31,25,31.0,Ouemo,True,3 ans,Chloelibaude69@gmail.com,False,4,3,2,...,3,1,4,4,4,4,4,2,2,1
32,26,-59.0,Ooémo,True,6 ans,niaouli@mls.nc,True,4,2,4,...,3,3,3,4,3,4,4,4,3,4
33,27,27.0,Vallée des colons,True,4,charlotte.daros@gmail.com,True,3,3,3,...,3,4,3,4,4,4,3,4,3,5
34,28,26.0,PK4,True,1 an,NaN,False,3,3,1,...,1,1,1,5,5,5,5,3,5,5
35,29,29.0,NaN,False,NaN,warrenmazoyer@hotmail.com,True,4,3,4,...,5,4,4,3,4,3,3,3,4,4
36,30,44.0,NaN,False,NaN,abisson@nautile.nc,False,3,3,3,...,5,3,3,3,3,3,3,3,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,279,30.0,Magenta,True,20,djcotexyo@hotmail.com,True,4,5,4,...,4,2,3,3,3,3,3,3,4,5
303,280,31.0,Ouemo,True,3 ans,antoinephilippe.simoni@gmail.com,False,3,3,3,...,3,5,3,3,4,3,3,3,3,3
304,281,-50.0,RIVIERE SALEE,True,6ANS,dugue1967@gmail.com,True,4,3,3,...,4,4,4,4,4,5,5,5,5,5
305,282,50.0,ouemo,True,20 ans,saubot.isabelle@gmail.com,True,3,3,4,...,4,3,3,4,4,3,3,3,4,3
306,283,35.0,NaN,False,NaN,NaN,False,3,4,4,...,4,3,3,3,3,4,3,3,3,3
307,284,33.0,NaN,False,NaN,amatnelson@gmail.com,False,4,3,3,...,1,5,2,4,4,5,3,3,1,3
308,285,44.0,NaN,False,NaN,NaN,False,4,2,5,...,4,4,3,4,4,4,3,4,3,3
309,286,33.0,Pk7,True,NaN,Snowawe@gmail.com,True,4,3,4,...,4,5,5,5,5,5,4,5,5,5
311,287,42.0,NaN,False,NaN,karine.ezzine@secal.nc,True,4,1,4,...,4,5,2,4,2,4,2,4,4,2
312,288,50.0,NaN,False,NaN,christophe.andre@province-sud.nc,True,4,3,3,...,3,4,3,3,4,3,3,3,4,3
313,289,46.0,Tuband,True,15 ans,valerie.klein-vervaele@province-sud.nc,True,3,2,3,...,3,2,4,2,4,4,4,4,4,4
314,290,60.0,vdc,True,10,NaN,False,4,3,3,...,5,3,3,3,3,3,3,3,3,3
315,291,68.0,Tina,True,11 ans,lemomic@canl.nc,True,4,4,4,...,4,5,3,4,4,4,3,4,4,5
316,292,NaN,NaN,True,NaN,NaN,False,2,4,3,...,4,3,4,3,4,4,3,3,4,3
317,293,40.0,vdc,True,NaN,NaN,False,4,1,4,...,4,4,3,3,3,3,3,3,5,5
318,294,29.0,NaN,False,NaN,NaN,False,4,4,4,...,2,3,2,4,3,3,3,3,1,3
319,295,35.0,NaN,False,NaN,NaN,False,1,3,3,...,3,2,3,2,3,3,3,3,3,3
321,296,51.0,Kaméré,True,25 ans,rousselot.sonia@yahoo.fr,False,5,5,5,...,5,1,1,3,1,5,1,5,5,5
322,297,51.0,Kaméré,True,25 ans,rousselot.sonia@yahoo.fr,True,5,5,5,...,5,1,1,3,1,5,1,5,5,5
323,298,45.0,Baie des citrons,True,10 ans,NaN,False,5,3,3,...,3,5,3,4,4,3,3,3,3,4
324,299,56.0,faubourg blanchot,True,29 ans,evilous27@outlook.fr,False,3,3,3,...,2,3,2,3,3,3,3,3,2,3
326,300,50.0,Val plaisance,True,5 ans,apeytaving@yahoo.fr,True,4,5,5,...,4,5,4,5,5,4,3,3,5,5
327,301,29.0,ouémo,True,3,audrey.bastonero@province-sud.nc,True,4,3,3,...,3,5,4,3,4,4,4,3,3,4
328,302,29.0,ouemo,True,2 ans,NaN,False,2,3,3,...,1,4,2,4,2,2,3,3,3,4
329,303,30.0,rivière salée,True,NaN,a.bonnefond@gmail.com,True,4,2,3,...,3,4,3,4,4,4,3,3,3,3
330,304,19.0,Magenta,True,19 ans,NaN,False,2,3,3,...,3,3,3,4,3,3,3,3,3,3
331,305,71.0,sud,True,10 ans,franfonba@corail.nc,True,3,2,3,...,2,3,2,4,2,3,2,3,3,4
332,306,33.0,TINDU,True,33 ANS,monia.diri@hotmail.com,False,4,4,4,...,5,4,4,4,4,4,3,3,3,3
333,307,NaN,NaN,False,NaN,ymelysabeth@gmail.com,True,2,4,5,...,3,1,1,4,1,4,3,5,5,5
335,308,30.0,NaN,False,NaN,jenna.tual@gmail.com,False,3,3,3,...,4,4,3,3,3,4,3,2,4,4

In [3]:
# correcting spelling variation
# next time using a levenstein correction
df['neighbourhood'] = df['neighbourhood'].str.lower().str.strip()
df['neighbourhood'] = df['neighbourhood'].replace(['tina sur mer', 'tina golf', 'tina/mer'], 'tina')
df['neighbourhood'] = df['neighbourhood'].replace(['vdc', 'vallée de clons', 'vallee des colons', 'vallée des clons'], 'vallée des colons')
df['neighbourhood'] = df['neighbourhood'].replace(['ooémo', 'ouemo'], 'ouémo')
df['neighbourhood'] = df['neighbourhood'].replace(['7eme km', '7ieme km', '7ème km', '7ème km ', 'pk 7', '6eme', '6ieme', '7em', '7km', '7emekm'], 'pk7')
df['neighbourhood'] = df['neighbourhood'].replace(['6eme km', '6ieme km', 'pk 6', '6eme', '6ieme', '6em', '6km', '6 km'], 'pk6')
df['neighbourhood'] = df['neighbourhood'].replace(['motor-pool', 'motor pool'], 'motorpool')
df['neighbourhood'] = df['neighbourhood'].replace(['centre ville', 'ville', 'port moselle'], 'centre-ville')
df['neighbourhood'] = df['neighbourhood'].replace(['ngea', "n'gea"], "n'géa")
df['neighbourhood'] = df['neighbourhood'].replace(['pdf', 'porte de fer', 'port de fer'], 'portes de fer')
df['neighbourhood'] = df['neighbourhood'].replace('bdc', 'baie des citrons')
df['neighbourhood'] = df['neighbourhood'].replace('latin', 'quartier latin')
df['neighbourhood'] = df['neighbourhood'].replace('rivière  salée', 'rivière salée')
df['neighbourhood'] = df['neighbourhood'].replace('faubourg', 'faubourg blanchot')
df['neighbourhood'] = df['neighbourhood'].replace('vdt2', 'vallée du tir')
df['neighbourhood'] = df['neighbourhood'].replace(['riviere salee', 'riviere sale', 'riviere salée', 'rivière-salée'], 'rivière-salée')
df['neighbourhood'] = df['neighbourhood'].replace('latin', 'quartier latin')
df['neighbourhood'] = df['neighbourhood'].replace(['saint marie', 'st marie', 'ste marie', 'sainte-marie'], 'sainte marie')
df['neighbourhood'] = df['neighbourhood'].replace('ducos papeete', 'ducos')
df['neighbourhood'] = df['neighbourhood'].replace(['pacifique arcade', 'artiellerie'], 'artillerie')

counts = df['neighbourhood'].value_counts()
counts

vallée des colons    23
ouémo                22
magenta              20
centre-ville         15
pk7                  12
trianon              12
anse vata            11
tina                 10
faubourg blanchot    10
val plaisance         9
pk6                   8
portes de fer         7
quartier latin        7
baie des citrons      6
rivière salée         6
n'géa                 6
motorpool             5
haut magenta          4
tuband                4
orphelinat            4
rivière-salée         4
artillerie            3
logicoop              3
kaméré                3
vallée du génie       2
pk4                   2
ducos                 2
vallée du tir         2
port plaisance        2
sainte marie          2
pont des francais     1
receiving             1
moselle               1
porte d'argent        1
vallée du genie       1
sud                   1
noumea                1
tindu                 1
normandie             1
anse-vata             1
hlm                   1
koutio                1
ouen toro             1
bais des pecheurs     1
haut-magenta          1
mont-coffyn           1
Name: neighbourhood, dtype: int64

In [6]:
# geocodes by neighborhood name
# NaN becomes string null
# clean this up, super ugly code ick
import geocoder
longitude = []
latitude = []
n_index = 0
for neighbourhood in df['neighbourhood']:
    if pd.isnull(neighbourhood) == False and type(neighbourhood) != float:
        place = "%s, %s" % (neighbourhood, 'Noumea')
        g = geocoder.google(place)
        g.latlng
        try: 
            lat = g.lat
            long = g.lng
            latitude.append(lat)
            longitude.append(long)
        except: 
            lat = 'null'
            long = 'null'
            latitude.append(lat)
            longitude.append(long)
    else: 
        lat = 'null'
        long = 'null'
        latitude.append(lat)
        longitude.append(long)
    print(df.index[n_index], neighbourhood, lat, long)
    n_index = n_index + 1
df['longitude'] = longitude
df['latitude'] = latitude

4 pk6 -22.245529 166.469435
5 magenta -22.2599055 166.4729372
7 trianon -22.2842354 166.4498013
8 nan null null
9 baie des citrons -22.291226 166.4375086
10 magenta -22.2599055 166.4729372
11 tuband -22.2926943 166.4548626
12 tuband -22.2926943 166.4548626
13 trianon -22.2842354 166.4498013
15 faubourg blanchot -22.2807684 166.4519704
16 trianon -22.2842354 166.4498013
17 vallée des colons -22.2706695 166.4534165
18 ouémo -22.2798021 166.475106
20 koutio -22.2015547 166.4649847
21 ouémo -22.2798021 166.475106
22 tina -22.2511452 166.4848346
23 magenta -22.2599055 166.4729372
24 pk7 -22.2363115 166.4757915
25 pk7 -22.2363115 166.4757915
26 nan null null
27 nan null null
28 nan null null
29 vallée des colons -22.2706695 166.4534165
30 faubourg blanchot -22.2807684 166.4519704
31 ouémo -22.2798021 166.475106
32 ouémo -22.2798021 166.475106
33 vallée des colons -22.2706695 166.4534165
34 pk4 -22.246884 166.463534
35 nan null null
36 nan null null
37 magenta -22.2599055 166.4729372
38 vallée des colons -22.2706695 166.4534165
39 magenta -22.2599055 166.4729372
40 nan null null
41 anse vata -22.3004763 166.4432935
42 magenta -22.2599055 166.4729372
43 vallée du genie -22.2693516 166.4475417
44 quartier latin -22.2765678 166.4454628
45 magenta -22.2599055 166.4729372
46 nan null null
47 vallée des colons -22.2706695 166.4534165
48 nan null null
49 nan null null
50 vallée des colons -22.2706695 166.4534165
51 pk6 -22.245529 166.469435
52 nan null null
53 nan null null
54 nan null null
55 centre-ville -22.2558234 166.4505243
56 vallée des colons -22.2706695 166.4534165
57 anse-vata -22.3004763 166.4432935
58 mont-coffyn -22.2796752 166.4468327
59 nan null null
61 nan null null
62 ouémo -22.2798021 166.475106
63 rivière salée -22.2307599 166.4649847
64 orphelinat -22.2853286 166.4454628
65 vallée du génie -22.2693516 166.4475417
66 pont des francais -22.2143316 166.4953463
67 centre-ville -22.2558234 166.4505243
68 porte d'argent -22.254813 166.462687
69 pk7 -22.2363115 166.4757915
70 trianon -22.2842354 166.4498013
71 n'géa -22.2897739 166.4548626
72 anse vata -22.3004763 166.4432935
73 magenta -22.2599055 166.4729372
74 pk6 -22.245529 166.469435
75 ducos -22.2409774 166.4476321
76 rivière-salée -22.2307599 166.4649847
77 tina -22.2511452 166.4848346
78 val plaisance -22.3012106 166.4519704
79 faubourg blanchot -22.2807684 166.4519704
80 n'géa -22.2897739 166.4548626
81 vallée des colons -22.2706695 166.4534165
82 nan null null
83 tuband -22.2926943 166.4548626
85 nan null null
86 portes de fer -22.2581384 166.4606468
87 portes de fer -22.2581384 166.4606468
88 tina -22.2511452 166.4848346
89 receiving -22.2925069 166.4440166
90 magenta -22.2599055 166.4729372
91 nan null null
92 bais des pecheurs -22.2905892 166.440096
93 portes de fer -22.2581384 166.4606468
96 anse vata -22.3004763 166.4432935
97 quartier latin -22.2765678 166.4454628
98 baie des citrons -22.291226 166.4375086
99 hlm -22.2735314 166.4395232
100 pk4 -22.246884 166.463534
101 val plaisance -22.3012106 166.4519704
102 nan null null
103 vallée des colons -22.2706695 166.4534165
104 rivière-salée -22.2307599 166.4649847
105 ducos -22.2409774 166.4476321
106 magenta -22.2599055 166.4729372
107 trianon -22.2842354 166.4498013
108 pk6 -22.245529 166.469435
109 pk7 -22.2363115 166.4757915
110 magenta -22.2599055 166.4729372
111 nan null null
112 nan null null
113 nan null null
114 trianon -22.2842354 166.4498013
115 anse vata -22.3004763 166.4432935
116 quartier latin -22.2765678 166.4454628
117 nan null null
118 baie des citrons -22.291226 166.4375086
119 vallée des colons -22.2706695 166.4534165
120 nan null null
121 anse vata -22.3004763 166.4432935
122 magenta -22.2599055 166.4729372
123 quartier latin -22.2765678 166.4454628
124 haut-magenta -22.263735 166.4577547
125 haut magenta -22.263735 166.4577547
126 ouémo -22.2798021 166.475106
127 n'géa -22.2897739 166.4548626
128 vallée des colons -22.2706695 166.4534165
129 nan null null
130 rivière salée -22.2307599 166.4649847
131 centre-ville -22.2558234 166.4505243
132 magenta -22.2599055 166.4729372
133 portes de fer -22.2581384 166.4606468
134 trianon -22.2842354 166.4498013
135 quartier latin -22.2765678 166.4454628
136 ouémo -22.2798021 166.475106
137 tina -22.2511452 166.4848346
138 nan null null
139 nan null null
140 vallée du tir -22.2619664 166.4454628
141 pk6 -22.245529 166.469435
142 nan null null
143 vallée des colons -22.2706695 166.4534165
144 nan null null
145 pk7 -22.2363115 166.4757915
146 motorpool -22.2922051 166.4490782
147 centre-ville -22.2558234 166.4505243
148 nan null null
149 nan null null
150 logicoop -22.2354973 166.4346161
151 nan null null
152 val plaisance -22.3012106 166.4519704
153 sainte marie -22.2790196 166.4573506
154 portes de fer -22.2581384 166.4606468
155 anse vata -22.3004763 166.4432935
156 motorpool -22.2922051 166.4490782
157 nan null null
159 nan null null
160 vallée des colons -22.2706695 166.4534165
161 nan null null
162 centre-ville -22.2558234 166.4505243
163 nan null null
165 n'géa -22.2897739 166.4548626
166 vallée des colons -22.2706695 166.4534165
167 baie des citrons -22.291226 166.4375086
168 nan null null
169 vallée du tir -22.2619664 166.4454628
170 centre-ville -22.2558234 166.4505243
171 nan null null
172 sainte marie -22.2790196 166.4573506
173 pk7 -22.2363115 166.4757915
174 anse vata -22.3004763 166.4432935
175 ouémo -22.2798021 166.475106
176 ouémo -22.2798021 166.475106
177 artillerie -22.2797899 166.4404011
178 vallée du génie -22.2693516 166.4475417
179 ouémo -22.2798021 166.475106
180 val plaisance -22.3012106 166.4519704
181 faubourg blanchot -22.2807684 166.4519704
182 noumea -22.2558234 166.4505243
183 quartier latin -22.2765678 166.4454628
184 pk7 -22.2363115 166.4757915
185 pk7 -22.2363115 166.4757915
186 motorpool -22.2922051 166.4490782
187 ouémo -22.2798021 166.475106
188 trianon -22.2842354 166.4498013
189 faubourg blanchot -22.2807684 166.4519704
190 vallée des colons -22.2706695 166.4534165
191 centre-ville -22.2558234 166.4505243
192 tina -22.2511452 166.4848346
193 ouémo -22.2798021 166.475106
194 vallée des colons -22.2706695 166.4534165
195 moselle -22.2778118 166.4385933
196 vallée des colons -22.2706695 166.4534165
197 nan null null
198 rivière-salée -22.2307599 166.4649847
199 magenta -22.2599055 166.4729372
200 rivière salée -22.2307599 166.4649847
201 tina -22.2511452 166.4848346
202 val plaisance -22.3012106 166.4519704
203 haut magenta -22.263735 166.4577547
204 anse vata -22.3004763 166.4432935
205 nan null null
206 nan null null
208 artillerie -22.2797899 166.4404011
209 pk7 -22.2363115 166.4757915
210 n'géa -22.2897739 166.4548626
212 rivière salée -22.2307599 166.4649847
214 logicoop -22.2354973 166.4346161
215 normandie -22.2252851 166.4866723
216 tina -22.2511452 166.4848346
217 nan null null
218 ouen toro -22.3072959 166.4548626
219 nan null null
220 tina -22.2511452 166.4848346
221 anse vata -22.3004763 166.4432935
222 tina -22.2511452 166.4848346
223 centre-ville -22.2558234 166.4505243
225 faubourg blanchot -22.2807684 166.4519704
227 nan null null
228 vallée des colons -22.2706695 166.4534165
229 faubourg blanchot -22.2807684 166.4519704
230 artillerie -22.2797899 166.4404011
231 ouémo -22.2798021 166.475106
232 ouémo -22.2798021 166.475106
233 pk6 -22.245529 166.469435
234 nan null null
235 nan null null
236 orphelinat -22.2853286 166.4454628
237 orphelinat -22.2853286 166.4454628
238 val plaisance -22.3012106 166.4519704
239 val plaisance -22.3012106 166.4519704
240 ouémo -22.2798021 166.475106
241 portes de fer -22.2581384 166.4606468
242 haut magenta -22.263735 166.4577547
243 trianon -22.2842354 166.4498013
244 trianon -22.2842354 166.4498013
245 nan null null
246 pk6 -22.245529 166.469435
247 trianon -22.2842354 166.4498013
248 centre-ville -22.2558234 166.4505243
250 motorpool -22.2922051 166.4490782
251 anse vata -22.3004763 166.4432935
252 nan null null
253 centre-ville -22.2558234 166.4505243
254 rivière salée -22.2307599 166.4649847
255 ouémo -22.2798021 166.475106
256 centre-ville -22.2558234 166.4505243
257 nan null null
258 vallée des colons -22.2706695 166.4534165
259 vallée des colons -22.2706695 166.4534165
260 port plaisance -22.2913102 166.4392662

261 baie des citrons -22.291226 166.4375086
262 nan null null
263 magenta -22.2599055 166.4729372
264 portes de fer -22.2581384 166.4606468
265 logicoop -22.2354973 166.4346161
266 orphelinat -22.2853286 166.4454628
267 pk7 -22.2363115 166.4757915
268 nan null null
269 magenta -22.2599055 166.4729372
270 centre-ville -22.2558234 166.4505243
271 ouémo -22.2798021 166.475106
272 port plaisance -22.2913102 166.4392662
273 motorpool -22.2922051 166.4490782
274 ouémo -22.2798021 166.475106
275 nan null null
276 nan null null
278 faubourg blanchot -22.2807684 166.4519704
279 nan null null
281 centre-ville -22.2558234 166.4505243
282 centre-ville -22.2558234 166.4505243
283 vallée des colons -22.2706695 166.4534165
285 val plaisance -22.3012106 166.4519704
287 pk6 -22.245529 166.469435
288 kaméré -22.2302036 166.4324466
289 nan null null
290 magenta -22.2599055 166.4729372
291 centre-ville -22.2558234 166.4505243
292 nan null null
293 n'géa -22.2897739 166.4548626
294 magenta -22.2599055 166.4729372
295 trianon -22.2842354 166.4498013
296 pk7 -22.2363115 166.4757915
297 quartier latin -22.2765678 166.4454628
298 faubourg blanchot -22.2807684 166.4519704
299 haut magenta -22.263735 166.4577547
301 anse vata -22.3004763 166.4432935
302 magenta -22.2599055 166.4729372
303 ouémo -22.2798021 166.475106
304 rivière-salée -22.2307599 166.4649847
305 ouémo -22.2798021 166.475106
306 nan null null
307 nan null null
308 nan null null
309 pk7 -22.2363115 166.4757915
311 nan null null
312 nan null null
313 tuband -22.2926943 166.4548626
314 vallée des colons -22.2706695 166.4534165
315 tina -22.2511452 166.4848346
316 nan null null
317 vallée des colons -22.2706695 166.4534165
318 nan null null
319 nan null null
321 kaméré -22.2302036 166.4324466
322 kaméré -22.2302036 166.4324466
323 baie des citrons -22.291226 166.4375086
324 faubourg blanchot -22.2807684 166.4519704
326 val plaisance -22.3012106 166.4519704
327 ouémo -22.2798021 166.475106
328 ouémo -22.2798021 166.475106
329 rivière salée -22.2307599 166.4649847
330 magenta -22.2599055 166.4729372
331 sud -22.2558234 166.4505243
332 tindu -22.2313542 166.4201523
333 nan null null
335 nan null null

In [8]:
# ensure that pandas doesn't round long/lat off
pd.set_option('precision',10)
df

,id,age,neighbourhood,lives_in_noumea,months_lived_in_noumea,email,enable_receive_emails,Étages: espaces educatifs,Bâtiments fermés au public pour réhabilitation,Maison du projet (accueil/ exposition),...,q5-2,q5-3,q5-4,q5-5,q5-6,q5-7,q5-8,q5-9,longitude,latitude
4,1,26.0,pk6,True,2 ans,jonathan.rebouillon@gmail.com,True,5,4,5,...,1,3,2,5,5,4,5,5,166.469435,-22.245529
5,2,30.0,magenta,True,30,Olivia.kurt@gmail.com,False,3,3,3,...,3,3,3,4,4,4,4,4,166.4729372,-22.2599055
7,3,32.0,trianon,True,22,ornc44@gmail.com,False,1,1,1,...,1,1,1,1,1,1,5,3,166.4498013,-22.2842354
8,4,28.0,NaN,False,NaN,e.launay@live.fr,True,3,3,4,...,3,4,3,3,3,1,5,5,null,null
9,5,26.0,baie des citrons,True,26 ans,haguet.megane@gmail.com,True,4,3,4,...,3,4,2,3,3,3,4,4,166.4375086,-22.291226
10,6,29.0,magenta,True,4,NaN,False,3,3,3,...,3,3,3,4,3,3,3,4,166.4729372,-22.2599055
11,7,46.0,tuband,True,10,fgambarotto@yahoo.fr,False,3,3,3,...,3,3,4,4,3,3,3,3,166.4548626,-22.2926943
12,8,46.0,tuband,True,10,fgambarotto@yahoo.fr,True,3,3,3,...,3,3,4,4,3,3,3,3,166.4548626,-22.2926943
13,9,37.0,trianon,True,3 ans,marie.brenon@lagoon.nc,True,5,5,4,...,4,4,4,3,3,5,4,3,166.4498013,-22.2842354
15,10,29.0,faubourg blanchot,True,1,marie.c.22@hotmail.fr,True,3,3,3,...,3,3,3,3,3,4,4,4,166.4519704,-22.2807684
16,11,63.0,trianon,True,12,micalonc@gmail.com,True,3,3,3,...,3,3,3,3,3,3,3,3,166.4498013,-22.2842354
17,12,48.0,vallée des colons,True,14,hregimbe@yahoo.fr,True,3,2,2,...,3,5,3,3,3,3,3,3,166.4534165,-22.2706695
18,13,25.0,ouémo,True,25 ans,boris.valin@gmail.com,True,2,3,2,...,5,5,5,5,5,5,5,5,166.475106,-22.2798021
20,14,31.0,koutio,True,NaN,hnatrsnj@hotmail.com,False,3,3,3,...,2,4,2,3,2,5,5,4,166.4649847,-22.2015547
21,15,47.0,ouémo,True,10 ans,sjouault@gmail.com,True,3,3,3,...,3,3,3,3,3,3,3,4,166.475106,-22.2798021
22,16,36.0,tina,True,NaN,gilamii@free.fr,True,3,4,2,...,3,5,3,5,2,3,3,5,166.4848346,-22.2511452
23,17,30.0,magenta,True,5,NaN,False,4,4,2,...,3,3,4,4,3,3,5,1,166.4729372,-22.2599055
24,18,35.0,pk7,True,9,caledoguide@gmail.com,True,4,3,4,...,2,2,2,4,1,3,4,4,166.4757915,-22.2363115
25,19,36.0,pk7,True,8 ans,franck.dominici@gmail.com,True,5,5,5,...,4,4,4,5,4,4,4,5,166.4757915,-22.2363115
26,20,26.0,NaN,False,NaN,amd.brt@gmail.com,True,3,3,3,...,3,3,4,3,3,3,3,5,null,null
27,21,31.0,NaN,False,NaN,sarltemad@gmail.com,False,4,4,4,...,4,4,4,4,4,4,4,4,null,null
28,22,NaN,NaN,False,NaN,NaN,False,3,3,3,...,1,1,1,1,1,1,1,1,null,null
29,23,30.0,vallée des colons,True,4 ans,NaN,False,4,1,4,...,1,3,1,4,2,2,1,3,166.4534165,-22.2706695
30,24,28.0,faubourg blanchot,True,NaN,Caroline.frickbaconnais@gmail.com,False,2,2,3,...,3,3,3,3,3,3,3,3,166.4519704,-22.2807684
31,25,31.0,ouémo,True,3 ans,Chloelibaude69@gmail.com,False,4,3,2,...,4,4,4,4,4,2,2,1,166.475106,-22.2798021
32,26,-59.0,ouémo,True,6 ans,niaouli@mls.nc,True,4,2,4,...,3,4,3,4,4,4,3,4,166.475106,-22.2798021
33,27,27.0,vallée des colons,True,4,charlotte.daros@gmail.com,True,3,3,3,...,3,4,4,4,3,4,3,5,166.4534165,-22.2706695
34,28,26.0,pk4,True,1 an,NaN,False,3,3,1,...,1,5,5,5,5,3,5,5,166.463534,-22.246884
35,29,29.0,NaN,False,NaN,warrenmazoyer@hotmail.com,True,4,3,4,...,4,3,4,3,3,3,4,4,null,null
36,30,44.0,NaN,False,NaN,abisson@nautile.nc,False,3,3,3,...,3,3,3,3,3,3,4,3,null,null
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,279,30.0,magenta,True,20,djcotexyo@hotmail.com,True,4,5,4,...,3,3,3,3,3,3,4,5,166.4729372,-22.2599055
303,280,31.0,ouémo,True,3 ans,antoinephilippe.simoni@gmail.com,False,3,3,3,...,3,3,4,3,3,3,3,3,166.475106,-22.2798021
304,281,-50.0,rivière-salée,True,6ANS,dugue1967@gmail.com,True,4,3,3,...,4,4,4,5,5,5,5,5,166.4649847,-22.2307599
305,282,50.0,ouémo,True,20 ans,saubot.isabelle@gmail.com,True,3,3,4,...,3,4,4,3,3,3,4,3,166.475106,-22.2798021
306,283,35.0,NaN,False,NaN,NaN,False,3,4,4,...,3,3,3,4,3,3,3,3,null,null
307,284,33.0,NaN,False,NaN,amatnelson@gmail.com,False,4,3,3,...,2,4,4,5,3,3,1,3,null,null
308,285,44.0,NaN,False,NaN,NaN,False,4,2,5,...,3,4,4,4,3,4,3,3,null,null
309,286,33.0,pk7,True,NaN,Snowawe@gmail.com,True,4,3,4,...,5,5,5,5,4,5,5,5,166.4757915,-22.2363115
311,287,42.0,NaN,False,NaN,karine.ezzine@secal.nc,True,4,1,4,...,2,4,2,4,2,4,4,2,null,null
312,288,50.0,NaN,False,NaN,christophe.andre@province-sud.nc,True,4,3,3,...,3,3,4,3,3,3,4,3,null,null
313,289,46.0,tuband,True,15 ans,valerie.klein-vervaele@province-sud.nc,True,3,2,3,...,4,2,4,4,4,4,4,4,166.4548626,-22.2926943
314,290,60.0,vallée des colons,True,10,NaN,False,4,3,3,...,3,3,3,3,3,3,3,3,166.4534165,-22.2706695
315,291,68.0,tina,True,11 ans,lemomic@canl.nc,True,4,4,4,...,3,4,4,4,3,4,4,5,166.4848346,-22.2511452
316,292,NaN,NaN,True,NaN,NaN,False,2,4,3,...,4,3,4,4,3,3,4,3,null,null
317,293,40.0,vallée des colons,True,NaN,NaN,False,4,1,4,...,3,3,3,3,3,3,5,5,166.4534165,-22.2706695
318,294,29.0,NaN,False,NaN,NaN,False,4,4,4,...,2,4,3,3,3,3,1,3,null,null
319,295,35.0,NaN,False,NaN,NaN,False,1,3,3,...,3,2,3,3,3,3,3,3,null,null
321,296,51.0,kaméré,True,25 ans,rousselot.sonia@yahoo.fr,False,5,5,5,...,1,3,1,5,1,5,5,5,166.4324466,-22.2302036
322,297,51.0,kaméré,True,25 ans,rousselot.sonia@yahoo.fr,True,5,5,5,...,1,3,1,5,1,5,5,5,166.4324466,-22.2302036
323,298,45.0,baie des citrons,True,10 ans,NaN,False,5,3,3,...,3,4,4,3,3,3,3,4,166.4375086,-22.291226
324,299,56.0,faubourg blanchot,True,29 ans,evilous27@outlook.fr,False,3,3,3,...,2,3,3,3,3,3,2,3,166.4519704,-22.2807684
326,300,50.0,val plaisance,True,5 ans,apeytaving@yahoo.fr,True,4,5,5,...,4,5,5,4,3,3,5,5,166.4519704,-22.3012106
327,301,29.0,ouémo,True,3,audrey.bastonero@province-sud.nc,True,4,3,3,...,4,3,4,4,4,3,3,4,166.475106,-22.2798021
328,302,29.0,ouémo,True,2 ans,NaN,False,2,3,3,...,2,4,2,2,3,3,3,4,166.475106,-22.2798021
329,303,30.0,rivière salée,True,NaN,a.bonnefond@gmail.com,True,4,2,3,...,3,4,4,4,3,3,3,3,166.4649847,-22.2307599
330,304,19.0,magenta,True,19 ans,NaN,False,2,3,3,...,3,4,3,3,3,3,3,3,166.4729372,-22.2599055
331,305,71.0,sud,True,10 ans,franfonba@corail.nc,True,3,2,3,...,2,4,2,3,2,3,3,4,166.4505243,-22.2558234
332,306,33.0,tindu,True,33 ANS,monia.diri@hotmail.com,False,4,4,4,...,4,4,4,4,3,3,3,3,166.4201523,-22.2313542
333,307,NaN,NaN,False,NaN,ymelysabeth@gmail.com,True,2,4,5,...,1,4,1,4,3,5,5,5,null,null
335,308,30.0,NaN,False,NaN,jenna.tual@gmail.com,False,3,3,3,...,3,3,3,4,3,2,4,4,null,null

In [10]:
# convert years to months

ans = re.compile(r"ans*")
digit = re.compile(r"\d+")

def multiple_replacer(*key_values):
    replace_dict = dict(key_values)
    replacement_function = lambda match: replace_dict[match.group(0)]
    pattern = re.compile("|".join([re.escape(k) for k, v in key_values]), re.M)
    return lambda string: pattern.sub(replacement_function, string)

def multiple_replace(string, *key_values):
    return multiple_replacer(*key_values)(string)

replacements = (u"un", u"1"), (u"deux", u"2"), (u"trois", u"3"), (u"quatre", u"4"), (u"cinq", u"5"), (u"six", u"6"), (u"sept", u"7"), (u"huit", u"8"), (u"neuf", u"9"), (u"dix", u"10"), (u"j'y suis née", u"toujours")
# print(multiple_replace(stringie, *replacements))

months_arr = []

# if the string contains years, multiply months * 12, remove 'ans'
for answer in df['months_lived_in_noumea']:
    has_ans = re.findall(ans, str(answer))
    print("initial", answer, type(answer), has_ans, len(has_ans))
    if len(has_ans) == 1:
        print(has_ans)
        number = re.findall(digit, str(answer))
        if len(number) != 0:
            new_answer = str(answer).lower()
            new_answer = multiple_replace(new_answer, *replacements)
            new_number = int(number[0]) * 12
            print(new_number)
            months_arr.append(str(new_number))
        else:
            months_arr.append(answer)
    else:
        print(answer)
        new_anwer = multiple_replace(str(answer), *replacements)
        print(new_answer)
        months_arr.append(new_answer)

# df['months_lived_in_noumea'] = months_arr
# print(months_arr)

initial 24 <class 'str'> [] 0
24
10 ans
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial nan <class 'float'> ['an'] 1
['an']
initial 312 <class 'str'> [] 0
312
2 ans
initial 26 ans <class 'str'> ['ans'] 1
['ans']
312
initial 26 ans <class 'str'> ['ans'] 1
['ans']
312
initial 26 ans <class 'str'> ['ans'] 1
['ans']
312
initial 36 <class 'str'> [] 0
36
26 ans
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial 300 <class 'str'> [] 0
300
3 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 120 <class 'str'> [] 0
120
3 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 10 ans <class 'str'> ['ans'] 1
['ans']
120
initial 10 ans <class 'str'> ['ans'] 1
['ans']
120
initial 96 <class 'str'> [] 0
96
10 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 48 <class 'str'> [] 0
48
10 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 36 <class 'str'> [] 0
36
10 ans
initial 72 <class 'str'> [] 0
72
10 ans
initial 6 ans <class 'str'> ['ans'] 1
['ans']
72
initial 12 <class 'str'> [] 0
12
6 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial 60 <class 'str'> [] 0
60
1 an
initial nan <class 'float'> ['an'] 1
['an']
initial 5 ans <class 'str'> ['ans'] 1
['ans']
60
initial 240 <class 'str'> [] 0
240
5 ans
initial 20 ans <class 'str'> ['ans'] 1
['ans']
240
initial 84 <class 'str'> [] 0
84
20 ans
initial 12 <class 'str'> [] 0
12
20 ans
initial 1 ans <class 'str'> ['ans'] 1
['ans']
12
initial nan <class 'float'> ['an'] 1
['an']
initial 60 <class 'str'> [] 0
60
1 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 12 <class 'str'> [] 0
12
1 ans
initial 84 <class 'str'> [] 0
84
1 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 60 <class 'str'> [] 0
60
1 ans
initial 72 <class 'str'> [] 0
72
1 ans
initial 48 <class 'str'> [] 0
48
1 ans
initial 84 <class 'str'> [] 0
84
1 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 7 ans <class 'str'> ['ans'] 1
['ans']
84
initial 36 <class 'str'> [] 0
36
7 ans
initial 360 <class 'str'> [] 0
360
7 ans
initial 12 <class 'str'> [] 0
12
7 ans
initial 204 <class 'str'> [] 0
204
7 ans
initial 17 ans  <class 'str'> ['ans'] 1
['ans']
204
initial 552 <class 'str'> [] 0
552
17 ans
initial 46 ans <class 'str'> ['ans'] 1
['ans']
552
initial 72 <class 'str'> [] 0
72
46 ans
initial 24 <class 'str'> [] 0
24
46 ans
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 252 <class 'str'> [] 0
252
2 ans
initial 21 ans <class 'str'> ['ans'] 1
['ans']
252
initial 180 <class 'str'> [] 0
180
21 ans
initial 396 <class 'str'> [] 0
396
21 ans
initial 60 <class 'str'> [] 0
60
21 ans
initial 5 ans <class 'str'> ['ans'] 1
['ans']
60
initial 5 ans <class 'str'> ['ans'] 1
['ans']
60
initial nan <class 'float'> ['an'] 1
['an']
initial 120 <class 'str'> [] 0
120
5 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 36 <class 'str'> [] 0
36
5 ans
initial 144 <class 'str'> [] 0
144
5 ans
initial 12 ans <class 'str'> ['ans'] 1
['ans']
144
initial 180 <class 'str'> [] 0
180
12 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 36 <class 'str'> [] 0
36
12 ans
initial 36 <class 'str'> [] 0
36
12 ans
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial nan <class 'float'> ['an'] 1
['an']
initial 72 <class 'str'> [] 0
72
3 ans
initial 6 ans <class 'str'> ['ans'] 1
['ans']
72
initial 6 ans <class 'str'> ['ans'] 1
['ans']
72
initial 96 <class 'str'> [] 0
96
6 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 720 <class 'str'> [] 0
720
6 ans
initial 60 ans <class 'str'> ['ans'] 1
['ans']
720
initial 180 <class 'str'> [] 0
180
60 ans
initial 36 <class 'str'> [] 0
36
60 ans
initial 120 <class 'str'> [] 0
120
60 ans
initial 180 <class 'str'> [] 0
180
60 ans
initial 15ans <class 'str'> ['ans'] 1
['ans']
180
initial 15ans <class 'str'> ['ans'] 1
['ans']
180
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 72 <class 'str'> [] 0
72
15ans
initial 6 and <class 'str'> ['an'] 1
['an']
72
initial 12 <class 'str'> [] 0
12
6 and
initial nan <class 'float'> ['an'] 1
['an']
initial 120 <class 'str'> [] 0
120
6 and
initial 12 <class 'str'> [] 0
12
6 and
initial nan <class 'float'> ['an'] 1
['an']
initial 12 <class 'str'> [] 0
12
6 and
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial nan <class 'float'> ['an'] 1
['an']
initial 96 <class 'str'> [] 0
96
1 an
initial 96 <class 'str'> [] 0
96
1 an
initial 144 <class 'str'> [] 0
144
1 an
initial 12 ans <class 'str'> ['ans'] 1
['ans']
144
initial 132 <class 'str'> [] 0
132
12 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 11 ans <class 'str'> ['ans'] 1
['ans']
132
initial 11 ans <class 'str'> ['ans'] 1
['ans']
132
initial 48 <class 'str'> [] 0
48
11 ans
initial 192 <class 'str'> [] 0
192
11 ans
initial 16 ans <class 'str'> ['ans'] 1
['ans']
192
initial 60 <class 'str'> [] 0
60
16 ans
initial 12 <class 'str'> [] 0
12
16 ans
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial nan <class 'float'> ['an'] 1
['an']
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial nan <class 'float'> ['an'] 1
['an']
initial 84 <class 'str'> [] 0
84
1 an
initial 7 ans <class 'str'> ['ans'] 1
['ans']
84
initial 36 <class 'str'> [] 0
36
7 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 60 <class 'str'> [] 0
60
7 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 12 <class 'str'> [] 0
12
7 ans
initial 120 <class 'str'> [] 0
120
7 ans
initial 10 ans <class 'str'> ['ans'] 1
['ans']
120
initial 10 ans <class 'str'> ['ans'] 1
['ans']
120
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 48 <class 'str'> [] 0
48
10 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 204 <class 'str'> [] 0
204
10 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 144 <class 'str'> [] 0
144
10 ans
initial 264 <class 'str'> [] 0
264
10 ans
initial 22 ans <class 'str'> ['ans'] 1
['ans']
264
initial nan <class 'float'> ['an'] 1
['an']
initial 22 ans <class 'str'> ['ans'] 1
['ans']
264
initial 22 ans <class 'str'> ['ans'] 1
['ans']
264
initial nan <class 'float'> ['an'] 1
['an']
initial 22 ans <class 'str'> ['ans'] 1
['ans']
264
initial 84 <class 'str'> [] 0
84
22 ans
initial 120 <class 'str'> [] 0
120
22 ans
initial 10 ans <class 'str'> ['ans'] 1
['ans']
120
initial 204 <class 'str'> [] 0
204
10 ans
initial 12 <class 'str'> [] 0
12
10 ans
initial 24 <class 'str'> [] 0
24
10 ans
initial 96 <class 'str'> [] 0
96
10 ans
initial 180 <class 'str'> [] 0
180
10 ans
initial 15 ans <class 'str'> ['ans'] 1
['ans']
180
initial 15 ans <class 'str'> ['ans'] 1
['ans']
180
initial 12 <class 'str'> [] 0
12
15 ans
initial 120 <class 'str'> [] 0
120
15 ans
initial 12 <class 'str'> [] 0
12
15 ans
initial 1 an <class 'str'> ['an'] 1
['an']
12
initial 360 <class 'str'> [] 0
360
1 an
initial 72 <class 'str'> [] 0
72
1 an
initial 348 <class 'str'> [] 0
348
1 an
initial 180 <class 'str'> [] 0
180
1 an
initial 15 ans <class 'str'> ['ans'] 1
['ans']
180
initial 12 <class 'str'> [] 0
12
15 ans
initial 36 <class 'str'> [] 0
36
15 ans
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial 36 <class 'str'> [] 0
36
3 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 60 <class 'str'> [] 0
60
3 ans
initial 204 <class 'str'> [] 0
204
3 ans
initial 432 <class 'str'> [] 0
432
3 ans
initial 324 <class 'str'> [] 0
324
3 ans
initial Huit ans <class 'str'> ['ans'] 1
['ans']
initial 240 <class 'str'> [] 0
240
3 ans
initial 20 ans <class 'str'> ['ans'] 1
['ans']
240
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 36 <class 'str'> [] 0
36
20 ans
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial nan <class 'float'> ['an'] 1
['an']
initial 156 <class 'str'> [] 0
156
3 ans
initial 48 <class 'str'> [] 0
48
3 ans
initial 4 ans <class 'str'> ['ans'] 1
['ans']
48
initial 288 <class 'str'> [] 0
288
4 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 24 ans <class 'str'> ['ans'] 1
['ans']
288
initial nan <class 'float'> ['an'] 1
['an']
initial 192 <class 'str'> [] 0
192
24 ans
initial 24 <class 'str'> [] 0
24
24 ans
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 48 <class 'str'> [] 0
48
2 ans
initial 84 <class 'str'> [] 0
84
2 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 7 ans <class 'str'> ['ans'] 1
['ans']
84
initial 96 <class 'str'> [] 0
96
7 ans
initial 36 <class 'str'> [] 0
36
7 ans
initial 504 <class 'str'> [] 0
504
7 ans
initial 144 <class 'str'> [] 0
144
7 ans
initial 168 <class 'str'> [] 0
168
7 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 12 <class 'str'> [] 0
12
7 ans
initial 12 <class 'str'> [] 0
12
7 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 24 <class 'str'> [] 0
24
7 ans
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 72 <class 'str'> [] 0
72
2 ans
initial 24 <class 'str'> [] 0
24
2 ans
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial nan <class 'float'> ['an'] 1
['an']
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 12 <class 'str'> [] 0
12
2 ans
initial 60 <class 'str'> [] 0
60
2 ans
initial 120 <class 'str'> [] 0
120
2 ans
initial 48 <class 'str'> [] 0
48
2 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 204 <class 'str'> [] 0
204
2 ans
initial 17 ans <class 'str'> ['ans'] 1
['ans']
204
initial 17 ans <class 'str'> ['ans'] 1
['ans']
204
initial 204 <class 'str'> [] 0
204
17 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 12 <class 'str'> [] 0
12
17 ans
initial 240 <class 'str'> [] 0
240
17 ans
initial 48 <class 'str'> [] 0
48
17 ans
initial 168 <class 'str'> [] 0
168
17 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 60 <class 'str'> [] 0
60
17 ans
initial 5 ans <class 'str'> ['ans'] 1
['ans']
60
initial 240 <class 'str'> [] 0
240
5 ans
initial 20 ans  <class 'str'> ['ans'] 1
['ans']
240
initial 20 ans  <class 'str'> ['ans'] 1
['ans']
240
initial nan <class 'float'> ['an'] 1
['an']
initial 20 ans  <class 'str'> ['ans'] 1
['ans']
240
initial nan <class 'float'> ['an'] 1
['an']
initial 20 ans  <class 'str'> ['ans'] 1
['ans']
240
initial 84 <class 'str'> [] 0
84
20 ans
initial 180 <class 'str'> [] 0
180
20 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 15ans <class 'str'> ['ans'] 1
['ans']
180
initial nan <class 'float'> ['an'] 1
['an']
initial 60 <class 'str'> [] 0
60
15ans
initial 60 <class 'str'> [] 0
60
15ans
initial 84 <class 'str'> [] 0
84
15ans
initial 228 <class 'str'> [] 0
228
15ans
initial 132 <class 'str'> [] 0
132
15ans
initial 72 <class 'str'> [] 0
72
15ans
initial nan <class 'float'> ['an'] 1
['an']
initial 6 ans <class 'str'> ['ans'] 1
['ans']
72
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 24 <class 'str'> [] 0
24
6 ans
initial 2 ans <class 'str'> ['ans'] 1
['ans']
24
initial 12 <class 'str'> [] 0
12
2 ans
initial 312 <class 'str'> [] 0
312
2 ans
initial 26 ans <class 'str'> ['ans'] 1
['ans']
312
initial 24 <class 'str'> [] 0
24
26 ans
initial 96 <class 'str'> [] 0
96
26 ans
initial 8 ans <class 'str'> ['ans'] 1
['ans']
96
initial 8 ans <class 'str'> ['ans'] 1
['ans']
96
initial 36 <class 'str'> [] 0
36
8 ans
initial 3 ans <class 'str'> ['ans'] 1
['ans']
36
initial 240 <class 'str'> [] 0
240
3 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 180 <class 'str'> [] 0
180
3 ans
initial 15 ans <class 'str'> ['ans'] 1
['ans']
180
initial 132 <class 'str'> [] 0
132
15 ans
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']
initial 300 <class 'str'> [] 0
300
15 ans
initial 300 <class 'str'> [] 0
300
15 ans
initial 120 <class 'str'> [] 0
120
15 ans
initial 348 <class 'str'> [] 0
348
15 ans
initial 60 <class 'str'> [] 0
60
15 ans
initial 5 ans <class 'str'> ['ans'] 1
['ans']
60
initial 24 <class 'str'> [] 0
24
5 ans
initial nan <class 'float'> ['an'] 1
['an']
initial 228 <class 'str'> [] 0
228
5 ans
initial 120 <class 'str'> [] 0
120
5 ans
initial 10 ans <class 'str'> ['ans'] 1
['ans']
120
initial nan <class 'float'> ['an'] 1
['an']
initial nan <class 'float'> ['an'] 1
['an']

In [ ]:
df

In [ ]:
# save to csv
df.to_csv('neighborhoods_aug31.csv', sep='\t')